### ISSUE TITLE
Sokoitsu and Konoitsu

### ISSUE THREAD

**Issue by Gh8stree** [Gideon9212/Livecustom#162]
[KonoSoko.zip](https://github.com/Gideon9212/Livecustom/files/1601276/KonoSoko.zip)
![konoitsu](https://user-images.githubusercontent.com/34216002/34533182-1fc42f68-f087-11e7-9449-01e79f4ce27b.jpg)
![sokoitsu](https://user-images.githubusercontent.com/34216002/34533183-1fd80010-f087-11e7-9e88-e3e0ff1172bb.jpg)

**Comment by rukudprime** [comment]
Hi, sorry to be leaving a comment like this.
I wanted to learn how to create a custom server and add cards to it, but I couldn't find out how.
Could you help me in any way possible? Thanks.
